version: 2.1
workflows:
  deploying:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: nazzim29/circle_runner
    steps:
      # - run: cd /var/infra-vost && gh repo sync && docker-compose up -d --remove-orphans
      - checkout
      - run:
          name: Run connected check on local runner
          command: cd /var/infra-vost && git pull && docker-compose --env-file /var/infra-vost/.env up -d --remove-orphans --build vost-api